export interface SurahInfo {
  nameTransliterated: string;
  nameEnglish: string;
}

export const SURAH_INFO: Record<number, SurahInfo> = {
  1:   { nameTransliterated: 'Al-Fatihah',     nameEnglish: 'The Opening' },
  2:   { nameTransliterated: 'Al-Baqarah',     nameEnglish: 'The Cow' },
  3:   { nameTransliterated: "Ali 'Imran",     nameEnglish: 'Family of Imran' },
  4:   { nameTransliterated: "An-Nisa'",       nameEnglish: 'The Women' },
  5:   { nameTransliterated: "Al-Ma'idah",     nameEnglish: 'The Table Spread' },
  6:   { nameTransliterated: "Al-An'am",       nameEnglish: 'The Cattle' },
  7:   { nameTransliterated: "Al-A'raf",       nameEnglish: 'The Heights' },
  8:   { nameTransliterated: 'Al-Anfal',       nameEnglish: 'The Spoils of War' },
  9:   { nameTransliterated: 'At-Tawbah',      nameEnglish: 'The Repentance' },
  10:  { nameTransliterated: 'Yunus',          nameEnglish: 'Jonah' },
  11:  { nameTransliterated: 'Hud',            nameEnglish: 'Hud' },
  12:  { nameTransliterated: 'Yusuf',          nameEnglish: 'Joseph' },
  13:  { nameTransliterated: "Ar-Ra'd",        nameEnglish: 'The Thunder' },
  14:  { nameTransliterated: 'Ibrahim',        nameEnglish: 'Abraham' },
  15:  { nameTransliterated: 'Al-Hijr',        nameEnglish: 'The Rocky Tract' },
  16:  { nameTransliterated: 'An-Nahl',        nameEnglish: 'The Bee' },
  17:  { nameTransliterated: "Al-Isra'",       nameEnglish: 'The Night Journey' },
  18:  { nameTransliterated: 'Al-Kahf',        nameEnglish: 'The Cave' },
  19:  { nameTransliterated: 'Maryam',         nameEnglish: 'Mary' },
  20:  { nameTransliterated: 'Ta-Ha',          nameEnglish: 'Ta-Ha' },
  21:  { nameTransliterated: "Al-Anbiya'",     nameEnglish: 'The Prophets' },
  22:  { nameTransliterated: 'Al-Hajj',        nameEnglish: 'The Pilgrimage' },
  23:  { nameTransliterated: "Al-Mu'minun",    nameEnglish: 'The Believers' },
  24:  { nameTransliterated: 'An-Nur',         nameEnglish: 'The Light' },
  25:  { nameTransliterated: 'Al-Furqan',      nameEnglish: 'The Criterion' },
  26:  { nameTransliterated: "Ash-Shu'ara'",   nameEnglish: 'The Poets' },
  27:  { nameTransliterated: 'An-Naml',        nameEnglish: 'The Ant' },
  28:  { nameTransliterated: 'Al-Qasas',       nameEnglish: 'The Stories' },
  29:  { nameTransliterated: 'Al-Ankabut',     nameEnglish: 'The Spider' },
  30:  { nameTransliterated: 'Ar-Rum',         nameEnglish: 'The Romans' },
  31:  { nameTransliterated: 'Luqman',         nameEnglish: 'Luqman' },
  32:  { nameTransliterated: 'As-Sajdah',      nameEnglish: 'The Prostration' },
  33:  { nameTransliterated: 'Al-Ahzab',       nameEnglish: 'The Combined Forces' },
  34:  { nameTransliterated: "Saba'",          nameEnglish: 'Sheba' },
  35:  { nameTransliterated: 'Fatir',          nameEnglish: 'Originator' },
  36:  { nameTransliterated: 'Ya-Sin',         nameEnglish: 'Ya-Sin' },
  37:  { nameTransliterated: 'As-Saffat',      nameEnglish: 'Those Who Set the Ranks' },
  38:  { nameTransliterated: 'Sad',            nameEnglish: 'The Letter Sad' },
  39:  { nameTransliterated: 'Az-Zumar',       nameEnglish: 'The Troops' },
  40:  { nameTransliterated: 'Ghafir',         nameEnglish: 'The Forgiver' },
  41:  { nameTransliterated: 'Fussilat',       nameEnglish: 'Explained in Detail' },
  42:  { nameTransliterated: 'Ash-Shura',      nameEnglish: 'The Consultation' },
  43:  { nameTransliterated: 'Az-Zukhruf',     nameEnglish: 'The Gold Adornments' },
  44:  { nameTransliterated: 'Ad-Dukhan',      nameEnglish: 'The Smoke' },
  45:  { nameTransliterated: 'Al-Jathiyah',    nameEnglish: 'The Crouching' },
  46:  { nameTransliterated: 'Al-Ahqaf',       nameEnglish: 'The Wind-Curved Sandhills' },
  47:  { nameTransliterated: 'Muhammad',       nameEnglish: 'Muhammad' },
  48:  { nameTransliterated: 'Al-Fath',        nameEnglish: 'The Victory' },
  49:  { nameTransliterated: 'Al-Hujurat',     nameEnglish: 'The Rooms' },
  50:  { nameTransliterated: 'Qaf',            nameEnglish: 'The Letter Qaf' },
  51:  { nameTransliterated: 'Adh-Dhariyat',   nameEnglish: 'The Winnowing Winds' },
  52:  { nameTransliterated: 'At-Tur',         nameEnglish: 'The Mount' },
  53:  { nameTransliterated: 'An-Najm',        nameEnglish: 'The Star' },
  54:  { nameTransliterated: 'Al-Qamar',       nameEnglish: 'The Moon' },
  55:  { nameTransliterated: 'Ar-Rahman',      nameEnglish: 'The Beneficent' },
  56:  { nameTransliterated: "Al-Waqi'ah",     nameEnglish: 'The Inevitable' },
  57:  { nameTransliterated: 'Al-Hadid',       nameEnglish: 'The Iron' },
  58:  { nameTransliterated: 'Al-Mujadila',    nameEnglish: 'The Pleading Woman' },
  59:  { nameTransliterated: 'Al-Hashr',       nameEnglish: 'The Exile' },
  60:  { nameTransliterated: 'Al-Mumtahanah',  nameEnglish: 'She That is to be Examined' },
  61:  { nameTransliterated: 'As-Saf',         nameEnglish: 'The Ranks' },
  62:  { nameTransliterated: "Al-Jumu'ah",     nameEnglish: 'The Congregation' },
  63:  { nameTransliterated: 'Al-Munafiqun',   nameEnglish: 'The Hypocrites' },
  64:  { nameTransliterated: 'At-Taghabun',    nameEnglish: 'The Mutual Disillusion' },
  65:  { nameTransliterated: 'At-Talaq',       nameEnglish: 'The Divorce' },
  66:  { nameTransliterated: 'At-Tahrim',      nameEnglish: 'The Prohibition' },
  67:  { nameTransliterated: 'Al-Mulk',        nameEnglish: 'The Sovereignty' },
  68:  { nameTransliterated: 'Al-Qalam',       nameEnglish: 'The Pen' },
  69:  { nameTransliterated: 'Al-Haqqah',      nameEnglish: 'The Reality' },
  70:  { nameTransliterated: "Al-Ma'arij",     nameEnglish: 'The Ascending Stairways' },
  71:  { nameTransliterated: 'Nuh',            nameEnglish: 'Noah' },
  72:  { nameTransliterated: 'Al-Jinn',        nameEnglish: 'The Jinn' },
  73:  { nameTransliterated: 'Al-Muzzammil',   nameEnglish: 'The Enshrouded One' },
  74:  { nameTransliterated: 'Al-Muddaththir', nameEnglish: 'The Cloaked One' },
  75:  { nameTransliterated: 'Al-Qiyamah',     nameEnglish: 'The Resurrection' },
  76:  { nameTransliterated: 'Al-Insan',       nameEnglish: 'The Human' },
  77:  { nameTransliterated: 'Al-Mursalat',    nameEnglish: 'The Emissaries' },
  78:  { nameTransliterated: "An-Naba'",       nameEnglish: 'The Tidings' },
  79:  { nameTransliterated: "An-Nazi'at",     nameEnglish: 'Those Who Drag Forth' },
  80:  { nameTransliterated: 'Abasa',          nameEnglish: 'He Frowned' },
  81:  { nameTransliterated: 'At-Takwir',      nameEnglish: 'The Overthrowing' },
  82:  { nameTransliterated: 'Al-Infitar',     nameEnglish: 'The Cleaving' },
  83:  { nameTransliterated: 'Al-Mutaffifin',  nameEnglish: 'The Defrauding' },
  84:  { nameTransliterated: 'Al-Inshiqaq',    nameEnglish: 'The Sundering' },
  85:  { nameTransliterated: 'Al-Buruj',       nameEnglish: 'The Mansions of the Stars' },
  86:  { nameTransliterated: 'At-Tariq',       nameEnglish: 'The Morning Star' },
  87:  { nameTransliterated: "Al-A'la",        nameEnglish: 'The Most High' },
  88:  { nameTransliterated: 'Al-Ghashiyah',   nameEnglish: 'The Overwhelming' },
  89:  { nameTransliterated: 'Al-Fajr',        nameEnglish: 'The Dawn' },
  90:  { nameTransliterated: 'Al-Balad',       nameEnglish: 'The City' },
  91:  { nameTransliterated: 'Ash-Shams',      nameEnglish: 'The Sun' },
  92:  { nameTransliterated: 'Al-Layl',        nameEnglish: 'The Night' },
  93:  { nameTransliterated: 'Ad-Duha',        nameEnglish: 'The Morning Hours' },
  94:  { nameTransliterated: 'Ash-Sharh',      nameEnglish: 'The Relief' },
  95:  { nameTransliterated: 'At-Tin',         nameEnglish: 'The Fig' },
  96:  { nameTransliterated: 'Al-Alaq',        nameEnglish: 'The Clot' },
  97:  { nameTransliterated: 'Al-Qadr',        nameEnglish: 'The Power' },
  98:  { nameTransliterated: 'Al-Bayyinah',    nameEnglish: 'The Clear Proof' },
  99:  { nameTransliterated: 'Az-Zalzalah',    nameEnglish: 'The Earthquake' },
  100: { nameTransliterated: 'Al-Adiyat',      nameEnglish: 'The Courser' },
  101: { nameTransliterated: "Al-Qari'ah",     nameEnglish: 'The Calamity' },
  102: { nameTransliterated: 'At-Takathur',    nameEnglish: 'The Rivalry in World Increase' },
  103: { nameTransliterated: 'Al-Asr',         nameEnglish: 'The Declining Day' },
  104: { nameTransliterated: 'Al-Humazah',     nameEnglish: 'The Traducer' },
  105: { nameTransliterated: 'Al-Fil',         nameEnglish: 'The Elephant' },
  106: { nameTransliterated: 'Quraysh',        nameEnglish: 'Quraysh' },
  107: { nameTransliterated: "Al-Ma'un",       nameEnglish: 'Small Kindnesses' },
  108: { nameTransliterated: 'Al-Kawthar',     nameEnglish: 'The Abundance' },
  109: { nameTransliterated: 'Al-Kafirun',     nameEnglish: 'The Disbelievers' },
  110: { nameTransliterated: 'An-Nasr',        nameEnglish: 'The Divine Support' },
  111: { nameTransliterated: 'Al-Masad',       nameEnglish: 'The Palm Fiber' },
  112: { nameTransliterated: 'Al-Ikhlas',      nameEnglish: 'The Sincerity' },
  113: { nameTransliterated: 'Al-Falaq',       nameEnglish: 'The Daybreak' },
  114: { nameTransliterated: 'An-Nas',         nameEnglish: 'Mankind' },
};

export function getSurahName(surahNumber: number): string {
  return SURAH_INFO[surahNumber]?.nameTransliterated ?? `Surah ${surahNumber}`;
}

export function getSurahInfo(surahNumber: number): SurahInfo {
  return SURAH_INFO[surahNumber] ?? { nameTransliterated: `Surah ${surahNumber}`, nameEnglish: '' };
}
