-- ============================================================
-- 006_enable_rls_and_policies.sql
-- Enable Row Level Security on all public application tables.
--
-- Architecture:
--   All data access goes through the Express backend, which uses:
--   - supabaseAdmin (Supabase service-role key) for Supabase JS
--     client calls
--   - pg Pool (Postgres superuser DATABASE_URL) for raw
--     transactions (BEGIN / COMMIT)
--
--   Both the service role and the postgres superuser bypass RLS
--   entirely. Enabling RLS with no additional policies therefore:
--   - Blocks all direct anon / authenticated role access
--   - Does NOT affect any existing backend behaviour
--   - Does NOT affect the Supabase Auth trigger
--     (handle_new_auth_user is SECURITY DEFINER → runs as its
--     definer (postgres), which is exempt from RLS)
--
-- Fire-and-forget mapping note (quran_page_mappings):
--   When a teacher creates an assignment, AssignmentService calls
--   quranContentService.getPageContent(pageNumber, false) in a
--   fire-and-forget manner to pre-populate quran_page_mappings.
--   If the Quran.Foundation prefetch fails (network error, rate
--   limit, etc.):
--   - Assignment creation still succeeds and returns 200.
--   - The failure is logged to stderr and never surfaced to the
--     caller.
--   - quran_page_mappings will be populated later the first time
--     any client fetches GET /api/quran/pages/:pageNumber/content
--     (getPageContent caches on first call via fetchAndCache).
--   - Until then, recalculateSnapshot produces a snapshot that
--     correctly counts pagesCompleted but with empty
--     surahBreakdown / juzBreakdown for that page.
--
-- Storage:
--   student-recordings and teacher-voice-notes are set to
--   private (public = false). All client object access is via
--   backend-generated signed URLs. Supabase verifies signed URL
--   JWTs at the storage API layer, independent of RLS.
-- ============================================================

-- ── Application tables ────────────────────────────────────────

ALTER TABLE users                         ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE device_tokens                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_assignment_requests   ENABLE ROW LEVEL SECURITY;
ALTER TABLE teacher_student_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_customers             ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans            ENABLE ROW LEVEL SECURITY;
ALTER TABLE quran_provider_resources      ENABLE ROW LEVEL SECURITY;
ALTER TABLE quran_pages                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE quran_page_mappings           ENABLE ROW LEVEL SECURITY;
ALTER TABLE surahs                        ENABLE ROW LEVEL SECURITY;
ALTER TABLE juzs                          ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE mistake_categories            ENABLE ROW LEVEL SECURITY;
ALTER TABLE mistake_options               ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE submission_attempts           ENABLE ROW LEVEL SECURITY;
ALTER TABLE annotations                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE annotation_voice_notes        ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_page_progress         ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_progress_snapshots    ENABLE ROW LEVEL SECURITY;

-- No additional policies are required or desired.
-- RLS enabled + zero policies = deny all for anon / authenticated.
-- Service role and postgres superuser (used by the pg Pool) bypass
-- RLS without needing any policy.

-- ── Storage buckets: enforce private access ───────────────────
-- public = false blocks all direct public URL access.
-- Signed URLs generated by the backend service role remain valid
-- (they are verified by the storage API, not by RLS policies).

UPDATE storage.buckets
SET    public = false
WHERE  name IN ('student-recordings', 'teacher-voice-notes');
